version: 2
jobs:
  build:
    working_directory: ~/circleci-Home-work16
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            yarn install
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - 'node_modules'
      - run:
          name: Lint code
          command: |
            yarn run lint1
      - run:
          name: Run test
          command: yarn run test
      - run:
          name: Test report
          command: yarn run coverage-report
      - store_artifacts:
          path: /coverage
      - run:
          name: Build docker image
          command: |
            docker login -u $DOCKER_CLOUD_USERNAME -p $DOCKER_CLOUD_PASSWORD
            docker build -t lerik1408/fixer-api:latest .
            docker push lerik1408/fixer-api:latest
#   deploy:
#     docker:
#       - image: buildpack-deps:trusty
#     steps:
#       - checkout
#       - run:
#           name: Deploy to Heroku
#           command: |
#             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master