version: 2
jobs:
  build:
    working_directory: ~/circleci-Home-work16
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            yarn install
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - 'node_modules'
      - run:
          name: Lint code
          command: |
            yarn run lint1
