openapi: 3.0.0
info:
  title: My Fixer API docs
  description: Made with Anton tutorial
  version: 0.0.1
  host: localhost:3000
tags:
  - name: Auth
  - name: Profile
  - name: Admin
  - name: Search
paths:
  /auth/sign-up:
    $ref: path/auth/signUp.yml
  /auth/sign-in:
    $ref: path/auth/signIn.yml
  /auth/check-email:
    $ref: path/auth/emailCheck.yml
  /auth/password:
    $ref: path/auth/password.yml
  /profile/person:
    $ref: path/profile/profile.yml
  /profile/photo:
    $ref: path/profile/photo.yml
  /admin/create-category:
    $ref: path/admin/createCategory.yml
  /search/people:
    $ref: path/search/people.yml
  /search/profile/{userId}:
    $ref: path/search/profile.yml
  /search/category:
    $ref: path/search/category.yml
servers:
  - url: /api
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
