openapi: 3.0.0
info:
  title: My Fixer API docs
  description: Made with ❤️️️️
  version: 0.0.1
  host: localhost:3000
tags:
  - name: Auth
paths:
  /auth/sign-up:
    $ref: path/auth/signUp.yml
servers:
  - url: /api
# components:
#   securitySchemes:
#     ApiKeyAuth:
#       type: apiKey
#       in: header
#       name: Authorization
# security:
#   - ApiKeyAuth: []
